### ISSUE TITLE
clarify  use of ExtendedSpecificDatumWriter in documentation

### ISSUE THREAD

**Issue by DJRickyB** [Celos/avro-json-encoder#1]
seems like it's required to use but it's not mentioned

**Comment by Celos** [comment]
Added a note in the readme. Thanks for reporting this.

**Comment by DJRickyB** [comment]
think you misread my text, I tried writing with this with a normal DatumWriter class but it didn't work until i used the bundled ExtendedSpecificDatumWriter

**Comment by Celos** [comment]
Right you are.
